### ISSUE TITLE
License changement

### ISSUE THREAD

**Issue by misha-plus** [beefsack/go-rate#10]
Hello. Thank you for good library.
But the license is GPL. Could you change the license to more permissive like Apache v2 or MIT. Because the library is so small. There is not so much code which is required to protect IMHO.

**Comment by beefsack** [comment]
Hi @misha-plus, thanks for the suggestion!

I'm happy with GPL, but also don't mind relicensing to MIT, and I realise nowadays it's much more popular and can fit better with some proprietary projects.

@matttproud are you happy to relicense your contributions in this project to MIT license? It has been some years since your contribution, but for a refresher these are the two commits: https://github.com/beefsack/go-rate/commits?author=matttproud

**Comment by matttproud** [comment]
Yes.

**Comment by shubham1172** [comment]
@beefsack would you accept a PR for changing the license?
